## File generated by the BNF Converter (bnfc 2.9.5).

CC = g++ -g
CCFLAGS = --ansi -std=c++20 -W -Wall -Wsign-conversion -Wno-unused-parameter -Wno-unused-function -Wno-unneeded-internal-declaration ${CC_OPTS}

FLEX = flex
FLEX_OPTS = -Pinstant_

BISON = bison
BISON_OPTS = -t -pinstant_

OBJS = Absyn.o Buffer.o Lexer.o Parser.o Printer.o
OBJS_FILES = build/Absyn.o  build/Buffer.o build/Lexer.o build/Parser.o build/Printer.o
.PHONY : clean distclean

all : TestInstant

clean :
	rm -f build/*.o src/TestInstant src/Instant.aux src/Instant.log src/Instant.pdf src/Instant.dvi src/Instant.ps src/Instant

distclean : clean
	rm -f Absyn.h Absyn.c Bison.h Buffer.h Buffer.c Instant.l Lexer.c Instant.y Parser.h Parser.c Printer.c Printer.h Skeleton.c Skeleton.h Test.c Makefile Instant.tex

TestInstant : ${OBJS} Test.o
	@echo "Linking TestInstant..."
	${CC} ${CCFLAGS} ${OBJS_FILES} build/Test.o -o build/TestInstant

Absyn.o : src/Absyn.c src/Absyn.h
	${CC} ${CCFLAGS} -c src/Absyn.c -o build/Absyn.o

Buffer.o : src/Buffer.c src/Buffer.h
	${CC} ${CCFLAGS} -c src/Buffer.c -o build/Buffer.o

Lexer.c : src/Instant.l
	${FLEX} ${FLEX_OPTS} -osrc/Lexer.c src/Instant.l

Parser.c Bison.h : src/Instant.y
	${BISON} ${BISON_OPTS} src/Instant.y -o src/Parser.c 

Lexer.o : CCFLAGS+=-Wno-sign-conversion

Lexer.o : src/Lexer.c src/Bison.h
	${CC} ${CCFLAGS} -c src/Lexer.c -o build/Lexer.o

Parser.o : src/Parser.c src/Absyn.h src/Bison.h
	${CC} ${CCFLAGS} -c src/Parser.c -o build/Parser.o

Printer.o : src/Printer.c src/Printer.h src/Absyn.h
	${CC} ${CCFLAGS} -c src/Printer.c -o build/Printer.o

Test.o : src/Test.cpp src/Parser.h src/Printer.h src/Absyn.h
	${CC} ${CCFLAGS} -c src/Test.cpp -o build/Test.o
