/* File generated by the BNF Converter (bnfc 2.9.5). */

/************************* Compiler Front-End Test *************************/
/*                                                                         */
/*  This test will parse a file, print the abstract syntax tree, and then  */
/*  pretty-print the result.                                               */
/*                                                                         */
/***************************************************************************/

#include "Includes.h"

void usage(void) {
  printf("usage: Call with one of the following argument combinations:\n");
  printf("\t--help\t\tDisplay this help message.\n");
  printf("\t(no arguments)\tParse stdin verbosely.\n");
  printf("\t(files)\t\tParse content of files verbosely.\n");
  printf("\t-s (files)\tSilent mode. Parse content of files silently.\n");
}

template<typename... Args>
std::string dyna_print(std::string_view rt_fmt_str, Args&&... args)
{
  return std::vformat(rt_fmt_str, std::make_format_args(args...));
}

int main(int argc, char ** argv)
{
  FILE *input;
  Program parse_tree;
  int quiet = 1;
  char *filename = NULL;

  if (argc > 1) {
    if (strcmp(argv[1], "-s") == 0) {
      quiet = 1;
      if (argc > 2) {
        filename = argv[2];
      } else {
        input = stdin;
      }
    } else {
      filename = argv[1];
    }
  }

  if (filename) {
    input = fopen(filename, "r");
    if (!input) {
      usage();
      exit(1);
    }
  }
  else input = stdin;
  
  parse_tree = pProgram(input);
  std::set<std::string> variables = collect_variables(parse_tree);
  size_t locals = variables.size();

  Data data;
  data.var_to_slots = create_map(variables);
  
  std::string generated_code = generate_code_jasmin(parse_tree,data);
  std::string start = R"abc(
.class public Main
.super java/lang/Object

.method public <init>()V
    aload_0
    invokenonvirtual java/lang/Object/<init>()V
    return
.end method
  
.method public static main([Ljava/lang/String;)V
.limit stack )abc";

  start+= std::to_string(data.max_stack_size)+"\n";
  start+=".limit locals "+std::to_string(locals+1)+"\n";
  std::string end = "return\n.end method";
  std::string jasmin_code = start + generated_code +end;

  std::ofstream myfile;
  myfile.open ("GeneratedFiles/generated_jasmin.j");
  myfile << jasmin_code;
  myfile.close();

  if (parse_tree)
  {
    if (!quiet) {
      printf("\n[Abstract Syntax]\n");
      printf("%s\n\n", showProgram(parse_tree));
      printf("[Linearized Tree]\n");
      printf("%s\n\n", printProgram(parse_tree));
    }
    free_Program(parse_tree);
    return 0;
  }

  return 1;
}