/* File generated by the BNF Converter (bnfc 2.9.5). */

#ifndef PARSER_HEADER_FILE
#define PARSER_HEADER_FILE

#include <stdio.h>
#include "Absyn.h"

Program  pProgram(FILE *inp);
Program psProgram(const char *str);
Stmt  pStmt(FILE *inp);
Stmt psStmt(const char *str);
ListStmt  pListStmt(FILE *inp);
ListStmt psListStmt(const char *str);
Exp  pExp1(FILE *inp);
Exp psExp1(const char *str);
Exp  pExp2(FILE *inp);
Exp psExp2(const char *str);
Exp  pExp3(FILE *inp);
Exp psExp3(const char *str);
Exp  pExp4(FILE *inp);
Exp psExp4(const char *str);
Exp  pExp(FILE *inp);
Exp psExp(const char *str);

#endif
