/* File generated by the BNF Converter (bnfc 2.9.5). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <ctype.h>   /* isspace */
#include <stddef.h>  /* size_t */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "Printer.h"

#define INDENT_WIDTH 2

int _n_;
char *buf_;
size_t cur_;
size_t buf_size;

/* You may wish to change the renderC functions */
void renderC(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppendC(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppendC('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppendC(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ' ') bufAppendC(c);
  else if (c == 0) return;
  else
  {
     bufAppendC(c);
     bufAppendC(' ');
  }
}

int allIsSpace(String s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return 0;
  return 1;
}

void renderS(String s)
{
  if (*s) /* s[0] != '\0', string s not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppendS(s);
    } else {
      bufAppendS(s);
      bufAppendC(' ');
    }
  }
}

void indent(void)
{
  int n = _n_;
  while (--n >= 0)
    bufAppendC(' ');
}

void backup(void)
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppendC('\n');
  indent();
}
char *printProgram(Program p)
{
  _n_ = 0;
  bufReset();
  ppProgram(p, 0);
  return buf_;
}
char *printStmt(Stmt p)
{
  _n_ = 0;
  bufReset();
  ppStmt(p, 0);
  return buf_;
}
char *printListStmt(ListStmt p)
{
  _n_ = 0;
  bufReset();
  ppListStmt(p, 0);
  return buf_;
}
char *printExp(Exp p)
{
  _n_ = 0;
  bufReset();
  ppExp(p, 0);
  return buf_;
}
char *showProgram(Program p)
{
  _n_ = 0;
  bufReset();
  shProgram(p);
  return buf_;
}
char *showStmt(Stmt p)
{
  _n_ = 0;
  bufReset();
  shStmt(p);
  return buf_;
}
char *showListStmt(ListStmt p)
{
  _n_ = 0;
  bufReset();
  shListStmt(p);
  return buf_;
}
char *showExp(Exp p)
{
  _n_ = 0;
  bufReset();
  shExp(p);
  return buf_;
}
void ppProgram(Program p, int _i_)
{
  switch(p->kind)
  {
  case Program_::is_Prog:
    if (_i_ > 0) renderC(_L_PAREN);
    ppListStmt(p->u.prog_.liststmt_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Program!\n");
    exit(1);
  }
}

void ppStmt(Stmt p, int _i_)
{
  switch(p->kind)
  {
  case Stmt_::is_SAss:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.sass_.ident_, 0);
    renderC('=');
    ppExp(p->u.sass_.exp_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case Stmt_::is_SExp:
    if (_i_ > 0) renderC(_L_PAREN);
    ppExp(p->u.sexp_.exp_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Stmt!\n");
    exit(1);
  }
}

void ppListStmt(ListStmt liststmt, int i)
{
  if (liststmt == 0)
  { /* nil */
  }
  else if (liststmt->liststmt_ == 0)
  { /* last */
    ppStmt(liststmt->stmt_, 0);
  }
  else
  { /* cons */
    ppStmt(liststmt->stmt_, 0);
    renderC(';');
    ppListStmt(liststmt->liststmt_, 0);
  }
}

void ppExp(Exp p, int _i_)
{
  switch(p->kind)
  {
  case Exp_::is_ExpAdd:
    if (_i_ > 1) renderC(_L_PAREN);
    ppExp(p->u.expadd_.exp_1, 2);
    renderC('+');
    ppExp(p->u.expadd_.exp_2, 1);
    if (_i_ > 1) renderC(_R_PAREN);
    break;

  case Exp_::is_ExpSub:
    if (_i_ > 2) renderC(_L_PAREN);
    ppExp(p->u.expsub_.exp_1, 2);
    renderC('-');
    ppExp(p->u.expsub_.exp_2, 3);
    if (_i_ > 2) renderC(_R_PAREN);
    break;

  case Exp_::is_ExpMul:
    if (_i_ > 3) renderC(_L_PAREN);
    ppExp(p->u.expmul_.exp_1, 3);
    renderC('*');
    ppExp(p->u.expmul_.exp_2, 4);
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case Exp_::is_ExpDiv:
    if (_i_ > 3) renderC(_L_PAREN);
    ppExp(p->u.expdiv_.exp_1, 3);
    renderC('/');
    ppExp(p->u.expdiv_.exp_2, 4);
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case Exp_::is_ExpLit:
    if (_i_ > 4) renderC(_L_PAREN);
    ppInteger(p->u.explit_.integer_, 0);
    if (_i_ > 4) renderC(_R_PAREN);
    break;

  case Exp_::is_ExpVar:
    if (_i_ > 4) renderC(_L_PAREN);
    ppIdent(p->u.expvar_.ident_, 0);
    if (_i_ > 4) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Exp!\n");
    exit(1);
  }
}

void ppInteger(Integer n, int i)
{
  char tmp[20];
  sprintf(tmp, "%d", n);
  renderS(tmp);
}
void ppDouble(Double d, int i)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  renderS(tmp);
}
void ppChar(Char c, int i)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
  bufAppendC(' ');
}
void ppString(String s, int i)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
  bufAppendC(' ');
}
void ppIdent(String s, int i)
{
  renderS(s);
}

void shProgram(Program p)
{
  switch(p->kind)
  {
  case Program_::is_Prog:
    bufAppendC('(');

    bufAppendS("Prog");

    bufAppendC(' ');

    shListStmt(p->u.prog_.liststmt_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Program!\n");
    exit(1);
  }
}

void shStmt(Stmt p)
{
  switch(p->kind)
  {
  case Stmt_::is_SAss:
    bufAppendC('(');

    bufAppendS("SAss");

    bufAppendC(' ');

    shIdent(p->u.sass_.ident_);
  bufAppendC(' ');
    shExp(p->u.sass_.exp_);

    bufAppendC(')');

    break;
  case Stmt_::is_SExp:
    bufAppendC('(');

    bufAppendS("SExp");

    bufAppendC(' ');

    shExp(p->u.sexp_.exp_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Stmt!\n");
    exit(1);
  }
}

void shListStmt(ListStmt liststmt)
{
  bufAppendC('[');
  while(liststmt != 0)
  {
    if (liststmt->liststmt_)
    {
      shStmt(liststmt->stmt_);
      bufAppendS(", ");
      liststmt = liststmt->liststmt_;
    }
    else
    {
      shStmt(liststmt->stmt_);
      liststmt = 0;
    }
  }
  bufAppendC(']');
}

void shExp(Exp p)
{
  switch(p->kind)
  {
  case Exp_::is_ExpAdd:
    bufAppendC('(');

    bufAppendS("ExpAdd");

    bufAppendC(' ');

    shExp(p->u.expadd_.exp_1);
  bufAppendC(' ');
    shExp(p->u.expadd_.exp_2);

    bufAppendC(')');

    break;
  case Exp_::is_ExpSub:
    bufAppendC('(');

    bufAppendS("ExpSub");

    bufAppendC(' ');

    shExp(p->u.expsub_.exp_1);
  bufAppendC(' ');
    shExp(p->u.expsub_.exp_2);

    bufAppendC(')');

    break;
  case Exp_::is_ExpMul:
    bufAppendC('(');

    bufAppendS("ExpMul");

    bufAppendC(' ');

    shExp(p->u.expmul_.exp_1);
  bufAppendC(' ');
    shExp(p->u.expmul_.exp_2);

    bufAppendC(')');

    break;
  case Exp_::is_ExpDiv:
    bufAppendC('(');

    bufAppendS("ExpDiv");

    bufAppendC(' ');

    shExp(p->u.expdiv_.exp_1);
  bufAppendC(' ');
    shExp(p->u.expdiv_.exp_2);

    bufAppendC(')');

    break;
  case Exp_::is_ExpLit:
    bufAppendC('(');

    bufAppendS("ExpLit");

    bufAppendC(' ');

    shInteger(p->u.explit_.integer_);

    bufAppendC(')');

    break;
  case Exp_::is_ExpVar:
    bufAppendC('(');

    bufAppendS("ExpVar");

    bufAppendC(' ');

    shIdent(p->u.expvar_.ident_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Exp!\n");
    exit(1);
  }
}

void shInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppendS(tmp);
}
void shDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppendS(tmp);
}
void shChar(Char c)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
}
void shString(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}
void shIdent(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}

void bufEscapeS(const char *s)
{
  if (s) while (*s) bufEscapeC(*s++);
}
void bufEscapeC(const char c)
{
  switch(c)
  {
    case '\f': bufAppendS("\\f" ); break;
    case '\n': bufAppendS("\\n" ); break;
    case '\r': bufAppendS("\\r" ); break;
    case '\t': bufAppendS("\\t" ); break;
    case '\v': bufAppendS("\\v" ); break;
    case '\\': bufAppendS("\\\\"); break;
    case '\'': bufAppendS("\\'" ); break;
    case '\"': bufAppendS("\\\""); break;
    default: bufAppendC(c);
  }
}

void bufAppendS(const char *s)
{
  size_t len = strlen(s);
  size_t n;
  while (cur_ + len >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  for(n = 0; n < len; n++)
  {
    buf_[cur_ + n] = s[n];
  }
  cur_ += len;
  buf_[cur_] = 0;
}
void bufAppendC(const char c)
{
  if (cur_ + 1 >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  buf_[cur_] = c;
  cur_++;
  buf_[cur_] = 0;
}
void bufReset(void)
{
  cur_ = 0;
  buf_size = BUFFER_INITIAL;
  resizeBuffer();
  memset(buf_, 0, buf_size);
}
void resizeBuffer(void)
{
  char *temp = (char *) malloc(buf_size);
  if (!temp)
  {
    fprintf(stderr, "Error: Out of memory while attempting to grow buffer!\n");
    exit(1);
  }
  if (buf_)
  {
    strncpy(temp, buf_, buf_size); /* peteg: strlcpy is safer, but not POSIX/ISO C. */
    free(buf_);
  }
  buf_ = temp;
}


