/* File generated by the BNF Converter (bnfc 2.9.5). */

/*** Visitor Traversal Skeleton. ***/
/* This traverses the abstract syntax tree.
   To use, copy Skeleton.h and Skeleton.c to
   new files. */

#include <stdlib.h>
#include <stdio.h>

#include "Skeleton.h"

void visitProgram(Program p)
{
  switch(p->kind)
  {
  case is_Prog:
    /* Code for Prog Goes Here */
    visitListStmt(p->u.prog_.liststmt_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Program!\n");
    exit(1);
  }
}

void visitStmt(Stmt p)
{
  switch(p->kind)
  {
  case is_SAss:
    /* Code for SAss Goes Here */
    visitIdent(p->u.sass_.ident_);
    visitExp(p->u.sass_.exp_);
    break;
  case is_SExp:
    /* Code for SExp Goes Here */
    visitExp(p->u.sexp_.exp_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Stmt!\n");
    exit(1);
  }
}

void visitListStmt(ListStmt liststmt)
{
  while(liststmt  != 0)
  {
    /* Code For ListStmt Goes Here */
    visitStmt(liststmt->stmt_);
    liststmt = liststmt->liststmt_;
  }
}

void visitExp(Exp p)
{
  switch(p->kind)
  {
  case is_ExpAdd:
    /* Code for ExpAdd Goes Here */
    visitExp(p->u.expadd_.exp_1);
    visitExp(p->u.expadd_.exp_2);
    break;
  case is_ExpSub:
    /* Code for ExpSub Goes Here */
    visitExp(p->u.expsub_.exp_1);
    visitExp(p->u.expsub_.exp_2);
    break;
  case is_ExpMul:
    /* Code for ExpMul Goes Here */
    visitExp(p->u.expmul_.exp_1);
    visitExp(p->u.expmul_.exp_2);
    break;
  case is_ExpDiv:
    /* Code for ExpDiv Goes Here */
    visitExp(p->u.expdiv_.exp_1);
    visitExp(p->u.expdiv_.exp_2);
    break;
  case is_ExpLit:
    /* Code for ExpLit Goes Here */
    visitInteger(p->u.explit_.integer_);
    break;
  case is_ExpVar:
    /* Code for ExpVar Goes Here */
    visitIdent(p->u.expvar_.ident_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Exp!\n");
    exit(1);
  }
}

void visitIdent(Ident i)
{
  /* Code for Ident Goes Here */
}
void visitInteger(Integer i)
{
  /* Code for Integer Goes Here */
}
void visitDouble(Double d)
{
  /* Code for Double Goes Here */
}
void visitChar(Char c)
{
  /* Code for Char Goes Here */
}
void visitString(String s)
{
  /* Code for String Goes Here */
}

